# Generated by Django 4.1.5 on 2023-01-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_created_time_user_guid_user_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('CODE_VERIFIED', 'CODE_VERIFIED'), ('INFORMATTION_FILLED', 'INFORMATTION_FILLED'), ('DONE', 'DONE')], default='NEW', max_length=31),
        ),
    ]
